### ISSUE TITLE
Little improvement

### ISSUE THREAD

**Issue by vystepanenko** [bedakb/vue-typeahead-component#1]
Thanks for great tutorial.

I want suggest one little improvement.
Your code for "li" item evoke an Vue warns

> Avoid using non-primitive value as key, use string/number value instead.

and 
> Duplicate keys detected: '[object Object]'. This may cause an update error.

You can use second parameter for v-for like this
```
           <li v-for="item, key in filtered" :key="key">
                <span>
                    //..
                </span>
            </li>
```
In this second parameter stores the element number. It will be primitive and will guarantee that all keys are unique

**Comment by bedakb** [comment]
Hi @vystepanenko thanks for pointing that out.

If you want, feel free to submit PR. :)

**Comment by bedakb** [comment]
Fixed with https://github.com/bedakb/vue-typeahead-component/pull/2
